name: SeleniumHub
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: RubbaBoy <email@example.com>

# pub run build_runner serve

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
#  angular: ^5.3.1
#  angular_components: ^0.13.0+1
  html: any
#  bootstrap_sass: any
#  sass_builder: ^2.1.2
  mime: ^0.9.6+3
  uuid: ^2.0.2
  recase: ^2.0.1
  clippy: ^1.0.0
  shelf_web_socket: ^0.2.3
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  angular: ^5.3.1
  args: ^1.5.2
  angel_proxy: ^2.1.2
  angel_framework: ^2.0.4+1

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4
  angular_components: ^0.13.0+1
  sass_builder: ^2.1.2

transformers:
  - angular:
      entry_points:
        - web/main.dart
        - test/**_test.dart
  - test/pub_serve:
      $include: test/**_test.dart
  - $dart2js:
      commandLineOptions: [--fast-startup, --minify]

targets:
  $default:
    builders:
      sass_builder:
        options:
          outputStyle: compressed