name: SeleniumHub
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: RubbaBoy <email@example.com>

# pub run build_runner serve

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  html: any
  bootstrap_sass: any
  sass_builder: ^2.1.1
  mime: ^0.9.6+3
  uuid: ^2.0.2

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.4

transformers:
  - angular:
      entry_points:
        - web/main.dart
        - test/**_test.dart
  - test/pub_serve:
      $include: test/**_test.dart
  - $dart2js:
      commandLineOptions: [--fast-startup, --minify]

targets:
  $default:
    builders:
      sass_builder:
        options:
          outputStyle: compressed